### PR TITLE
Use caller_locations to reduce memory allocation

### PR DESCRIPTION
**Pull request by dotai2012**
Before:
image

After:
image

### CODE REVIEW

**Comment by fatkodima** [comment]
We are also seeing a 10% time spent in this method.
```
▶ stackprof /var/folders/fz/3t9c9w9n3gj8hdq6l1r6qhgr0000gn/T/stackprof20231229-12091-subybx.dump --method 'Marginalia::Comment.line'
Marginalia::Comment.line (/Users/fatkodima/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/marginalia-1.11.1/lib/marginalia/comment.rb:112)
  samples:   510 self (0.3%)  /   15702 total (9.3%)
  callers:
    15702  (  100.0%)  Marginalia::Comment.construct_comment
    4958  (   31.6%)  Enumerable.detect
  callees (15192 total):
    9719  (   64.0%)  Kernel.caller
    5361  (   35.3%)  Enumerable.detect
    4666  (   30.7%)  Kernel.!~
     116  (    0.8%)  Rails.root
      86  (    0.6%)  Pathname#to_s
      73  (    0.5%)  Marginalia::Comment.lines_to_ignore
      68  (    0.4%)  String#[]
      41  (    0.3%)  Kernel.respond_to?
      20  (    0.1%)  String#start_with?
```

Can you squash the commits?

**Comment by hlascelles** [comment]
Nice change :+1:.

NB though all, Rails' (now) native version works the same way and recommends not using in production: https://guides.rubyonrails.org/debugging_rails_applications.html#verbose-query-logs

```
We recommend against using this setting in production environments. It relies on Ruby's Kernel#caller
method which tends to allocate a lot of memory in order to generate stacktraces of method calls.
Use query log tags (see below) instead.
```

So, I assume the same advice applies here. If you are really seeing high usage in prod due to Marginalia, consider disabling it completely.

**Comment by byroot** [comment]
I rebased it to fix the minitest issue, but now some tests are failing and look legitimate.

**Comment by nmdoliveira** [comment]
Hello!
Are you going to release a new version of the gem with this change?

**Pull request closed without merging**
