### PR TITLE
Customizable key-value separator and quoting

### PR DESCRIPTION
**Pull request by glebm**
This is to make it easier to parse these comments from logs.

### CODE REVIEW

**Comment by odeke-em** [comment]
Kindly pinging the marginalia authors, how is it going here? Is this PR one that we can examine? Thanks.

**Comment by balachandr** [comment]
@glebm , can you rebase and check if Travis is passing.

**Comment by odeke-em** [comment]
@balachandr I think he mailed PR https://github.com/basecamp/marginalia/pull/90 to fix the Travis build and that PR passes.

**Comment by odeke-em** [comment]
Kindly pinging @arthurnn @sharshenov to please take a look at this PR.

**Comment by sharshenov** [comment]
@odeke-em Unfortunately, I'm not a maintainer and I don't have rights to merge.

**Comment by lucasgomide** [comment]
@glebm Any update about that?

**Comment by glebm** [comment]
I won't be rebasing this, feel free to pick it up and do it

**Comment by modulitos** [comment]
Hi all - I've done a re-take of this PR from my fork here: https://github.com/basecamp/marginalia/pull/130

The tests are passing and I can confirm that the smoke tests are passing as well. Let me know if there's anything else I can do to get this reviewed :)

**Comment by jeremy** [comment]
Thanks @glebm. Superseded by #130.

**Pull request closed without merging**
