### PR TITLE
Avoiding mysql2 0.4.1 which does not load database adapter

### PR DESCRIPTION
**Pull request by compwron**
````
Run options: --seed 9869

# Running:

[ActiveJob] Enqueued PostsJob (Job ID: f905141a-7d7f-47c4-a2fc-2e007f7a9d44) to Inline(default)
[ActiveJob] [PostsJob] [f905141a-7d7f-47c4-a2fc-2e007f7a9d44] Performing PostsJob from Inline(default)
[ActiveJob] [PostsJob] [f905141a-7d7f-47c4-a2fc-2e007f7a9d44] Performed PostsJob from Inline(default) in 10.55ms
............

Finished in 0.028879s, 415.5268 runs/s, 796.4264 assertions/s.

12 runs, 23 assertions, 0 failures, 0 errors, 0 skips
DRIVER=mysql2 ruby -Ilib -Itest test/*_test.rb
/Users/hi/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /Users/hi/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
	from /Users/hi/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from test/query_comments_test.rb:50:in `<main>'
rake aborted!
````

### CODE REVIEW

**Comment by arthurnn** [comment]
I still didnt understand what's the proble with mysql2 2.4.1. Can you expand ?

**Comment by compwron** [comment]
For mysql2 https://rubygems.org/gems/mysql2/versions/0.4.1 as in the gemfile at https://github.com/basecamp/marginalia/blob/225b804ebc561c4d1587fc5ea3292880bb512004/marginalia.gemspec#L18
When I use 0.4.1 I see the above error. When I use 0.4.0 (also other, older versions) I do not.

**Comment by arthurnn** [comment]
the reason is that rails dont support mysql2 0.4+, see the fix on master and 4.2.5+ https://github.com/rails/rails/commit/2dfff4d31634d669f4c198c4fb85b59d39477862

**Comment by arthurnn** [comment]
https://github.com/basecamp/marginalia/commit/4d9c4871b7602d56df573568724b7d663a217f6a should fix the issue.

thanks for the PR anyways

**Pull request closed without merging**
