### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by gogainda** [comment]
@byroot pls review/merge

**Comment by byroot** [comment]
What's the goal here? Marginalia is a very simple gem, why does it need to be tested against truffle-head?

**Comment by gogainda** [comment]
once tests are passing against truffleruby(like here) we are adding it to the list of supported gems here https://github.com/eregon/truffleruby-gem-tracker It will help us to track any regressions which may occur during development

**Comment by byroot** [comment]
The thing is I can't think of anything in Marginalia that would break on Truffle, that wouldn't already break in dozens if not hundreds of other gems. 

If it was a stable release then maybe, but running `-head` without marking it as allowing failure is a support burden.

Also this makes CI 7 times slower. I really don't see the usefulness really.

**Comment by sj26** [comment]
Thanks, but CI has been moved to GitHub Actions in #124.

**Pull request closed without merging**
