### PR TITLE
Include Sidekiq Instrumentation

### PR DESCRIPTION
**Pull request by sribalakumar**
Ideal for Sidekiq instrumentation when ActiveJob is not available, apt for Rails < 4.2.

Can be turned on by configurting an initializer : 

e.g) config/initializers/marginalia.rb
```
Marginalia::Comment.components = [:sidekiq_job]
Marginalia::SidekiqInstrumentation.enable!
```

### CODE REVIEW

**Comment by sribalakumar** [comment]
@arthurnn Any updates on this PR ? :)

**Comment by sribalakumar** [comment]
@arthurnn Looking forward to hear your review comments and if there is anything more, I am eagerly waiting to add on.

**Comment by evsasse** [comment]
@arthurnn I would also appreciate a review/update about this.

**Comment by arthurnn** [comment]
sorry this took a while

**Pull request merged**
