### PR TITLE
Added failing test for exists

### PR DESCRIPTION
**Pull request by ankane**
`exists?` queries are not annotated with Rails 4.2.3 and the PostgreSQL adapter. Looked briefly at the relevant Rails source, but thought you may know the best way forward.

### CODE REVIEW

**Comment by arthurnn** [comment]
any clue why the test is passing tho?

**Comment by ankane** [comment]
It passes with some seeds and fails with others (probably a test order issue).  Here's one that's failing for me.

```sh
DRIVER=postgresql DB_USERNAME=postgres bundle exec ruby -Ilib -Itest test/*_test.rb --seed 21344
```

Also seeing it in production.

**Comment by arthurnn** [comment]
interesting, i wonder why travis ci dont show that failing error.
anyways, this seems like a bug to me. If you have time and interest to fix it, go ahead. otherwise i will take a look when i have some free time

**Comment by ankane** [comment]
This was occasionally passing because ActiveRecord sometimes loads the table structure first, which has the query comment. It may be good to change all the tests to `@queries.last` to avoid this.

```ruby
              SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"posts"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
 /*application:rails*/
```

**Pull request closed without merging**
